/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompanionsRouteImport } from './routes/companions'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanionsIdRouteImport } from './routes/companions.$id'

const CompanionsRoute = CompanionsRouteImport.update({
  id: '/companions',
  path: '/companions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionsIdRoute = CompanionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompanionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/companions': typeof CompanionsRouteWithChildren
  '/companions/$id': typeof CompanionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/companions': typeof CompanionsRouteWithChildren
  '/companions/$id': typeof CompanionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/companions': typeof CompanionsRouteWithChildren
  '/companions/$id': typeof CompanionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/companions' | '/companions/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/companions' | '/companions/$id'
  id: '__root__' | '/' | '/chat' | '/companions' | '/companions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CompanionsRoute: typeof CompanionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/companions': {
      id: '/companions'
      path: '/companions'
      fullPath: '/companions'
      preLoaderRoute: typeof CompanionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companions/$id': {
      id: '/companions/$id'
      path: '/$id'
      fullPath: '/companions/$id'
      preLoaderRoute: typeof CompanionsIdRouteImport
      parentRoute: typeof CompanionsRoute
    }
  }
}

interface CompanionsRouteChildren {
  CompanionsIdRoute: typeof CompanionsIdRoute
}

const CompanionsRouteChildren: CompanionsRouteChildren = {
  CompanionsIdRoute: CompanionsIdRoute,
}

const CompanionsRouteWithChildren = CompanionsRoute._addFileChildren(
  CompanionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CompanionsRoute: CompanionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
