/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompanionsRouteImport } from './routes/companions'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanionsIndexRouteImport } from './routes/companions.index'
import { Route as CompanionsIdRouteImport } from './routes/companions.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionsRoute = CompanionsRouteImport.update({
  id: '/companions',
  path: '/companions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionsIndexRoute = CompanionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanionsRoute,
} as any)
const CompanionsIdRoute = CompanionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompanionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/companions': typeof CompanionsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/companions/$id': typeof CompanionsIdRoute
  '/companions/': typeof CompanionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/companions/$id': typeof CompanionsIdRoute
  '/companions': typeof CompanionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/companions': typeof CompanionsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/companions/$id': typeof CompanionsIdRoute
  '/companions/': typeof CompanionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/companions'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/companions/$id'
    | '/companions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/companions/$id'
    | '/companions'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/companions'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/companions/$id'
    | '/companions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CompanionsRoute: typeof CompanionsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companions': {
      id: '/companions'
      path: '/companions'
      fullPath: '/companions'
      preLoaderRoute: typeof CompanionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companions/': {
      id: '/companions/'
      path: '/'
      fullPath: '/companions/'
      preLoaderRoute: typeof CompanionsIndexRouteImport
      parentRoute: typeof CompanionsRoute
    }
    '/companions/$id': {
      id: '/companions/$id'
      path: '/$id'
      fullPath: '/companions/$id'
      preLoaderRoute: typeof CompanionsIdRouteImport
      parentRoute: typeof CompanionsRoute
    }
  }
}

interface CompanionsRouteChildren {
  CompanionsIdRoute: typeof CompanionsIdRoute
  CompanionsIndexRoute: typeof CompanionsIndexRoute
}

const CompanionsRouteChildren: CompanionsRouteChildren = {
  CompanionsIdRoute: CompanionsIdRoute,
  CompanionsIndexRoute: CompanionsIndexRoute,
}

const CompanionsRouteWithChildren = CompanionsRoute._addFileChildren(
  CompanionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CompanionsRoute: CompanionsRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
